version: '3.8'

services:

    web:
    build: ../.
    restart: always
    volumes:
      - /etc/letsencrypt/live/revadamiller.ru/:/etc/letsencrypt/live/revadamiller.ru/
      - static_value:/app/static/
      - media_value:/app/media/

    nginx:
      image: nginx:1.21.3-alpine
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./var/html:/var/html
        - /etc/letsencrypt/:/etc/letsencrypt/
        - static_value:/var/html/static/
        - media_value:/var/html/media/
      depends_on:
        - web

  #  certbot:
  #    image: certbot/certbot
  #    volumes:
  #      - /etc/letsencrypt:/etc/letsencrypt
  #      - /var/lib/letsencrypt:/var/lib/letsencrypt
  #      - ./var/html:/var/html

volumes:
  static_value:
  media_value:
